### ISSUE TITLE
[BUG] - XBOX App error 0x89235107 after login

### ISSUE THREAD

**Issue by braindeadz** [Atlas-OS/Atlas#1044]
### Description

Hi everyone, 
First & fresh installation of Atlas OS
I try to login my xbox account to play with game pass but impossible, error 0x89235107.

### Steps to reproduce

![image](https://github.com/Atlas-OS/Atlas/assets/46479276/19762233-0ff8-48a7-a53d-ba52caffc884)
![image](https://github.com/Atlas-OS/Atlas/assets/46479276/f5b5ddc8-f0fa-4ba5-95c7-306d977ad529)
![image](https://github.com/Atlas-OS/Atlas/assets/46479276/e1ab9dec-cf7f-4b00-a67d-148ceaba4f65)
![image](https://github.com/Atlas-OS/Atlas/assets/46479276/9005318e-b11d-472a-aebe-49791de0f4d7)

### Expected behavior

I just want to connect my gamepass

### Actual behavior

![image](https://github.com/Atlas-OS/Atlas/assets/46479276/140ee2f3-e5ba-4cdd-b165-8d65f2cdbb87)

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

-AMD Ryzen 5 5600X
-GIGABYTE X570 I AORUS PRO WIFI
-Zotac RTX 3060 AMP Twin Edge LHR 12 GB
-32 Go DDR4 SDRAM 1333.0 MHz

### Additional content

Thanks !

**Comment by braindeadz** [comment]
I will try to reinstall Windows 11 and Atlas

**Comment by JayXTQ** [comment]
Is this issue on the latest build on the main branch? Or just 0.3.2? Because if 0.3.2 then this may already be fixed in a later commit

**Comment by braindeadz** [comment]
FIXED ! 

How ? 

Fresh new install of Windows 11 (Official ISO, media tool)

**Comment by CodingMadness** [comment]
Guys, you should mark those fixed issues as "closed" , its abit hard to track waht is not fixed else

**Comment by henders1** [comment]
u need to have microsoft edge installed to login, after installing it reset the app data in the windows settings of any xbox apps

**Comment by Xyueta** [comment]
This seems to be resolved.

Thanks.

**Comment by bahaajobs** [comment]
You will face this issue usally if you are using a modified windows version like Ghost Spectre, you will need to install Edge and Webview2 mannually. also make sure the the xbox and MS Market place are installed and the serivce is running.

please if this comment fixed your issue help your community by mentioing this, thanks
