### ISSUE TITLE
[BUG REPORT] - UAC bug ?

### ISSUE THREAD

**Issue by omerakgoz34** [Atlas-OS/Atlas#696]
### Description

I can not open Riot Repair Tool as admin. I tried every way to open it as admin but it still says not running as admin. This never happened before and it's the same version everyone uses for 3 years.

### Steps to reproduce (add screenshots if applicable)

right click > open as admin
or any other way to open as admin.
even tried to disable UAC completely with the Atlas script

### Expected behavior

I should open as admin c:

### Actual behavior (add screenshots if applicable)

![Screenshot_32](https://user-images.githubusercontent.com/49201485/233175673-e5048b7b-5a1b-47fd-ad2e-70b4cd06297d.png)

### Atlas Version

Atlas 10 22H2

### Desktop information

Original Windows ISO created with Microsoft tool.
Windows 10 22H2 19045.2846
I don't know why but Windows doesn't want to install the version 19045.29 update :/

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by omerakgoz34** [comment]
I didnt changed anything UAC related and tried disabling and reenabling it again with the atlas script after the issue happened.

**Comment by JayXTQ** [comment]
This doesn't seem like an Atlas issue because if you run with Admin... it should run with... Admin? But anyway, what I'd say is try running the app with NSudo which you can do by entering `nsudo` in the `Windows + R` box. Hopefully this helps

**Comment by omerakgoz34** [comment]
It must be Atlas issue bc the app didnt updated since 2020 and it always worked in every windows versions I tried. MSDN, lite etc...

"Can not find nsudo"

**Comment by JayXTQ** [comment]
If Run can't find NSudo, Atlas may not be installed correctly. Please try reinstalling.

**Comment by Xyueta** [comment]
NSudo is removed from Atlas, as we have the alternative of RunAsTI script. UAC is enabled on default.

**Comment by JayXTQ** [comment]
@Xyueta how's it going?

**Comment by Xyueta** [comment]
on my list to test :D

**Comment by Xyueta** [comment]
Latest release should fix it.

**Comment by omerakgoz34** [comment]
I'm using atlas v3.2 with win10 19045.3633 but it still not work. I check it from Task Manager and it's actually running as admin but still says me it's not running as admin, weird. Also the log collection function of it is no longer even works. Idk if it's due to the UAC problem or the program itself.

I think, it's too out-of-date and no longer works on newer versions of windows. I couldn't test it on vanilla windows.

**Comment by omerakgoz34** [comment]
It works now with v0.4 on win10 19045.4412 👍
