### ISSUE TITLE
[FEATURE REQUEST] - Question in wizard to keep radio communications(Bluetooth/ Wi-Fi)

### ISSUE THREAD

**Issue by rwkyyy** [Atlas-OS/Atlas#739]
### What is your Feature Request regarding to?

The Atlas OS

### Is your feature request related to a problem? Please describe.

My problem was that after reboot I had no radio communication, I am running a dedicated wifi network for my pc and phone, very stable connection, very low latency - I have read the docs and knew about this, but still I am unable to restore the BT one (irelevant at this point).

### Describe the solution you would like.

In the wizard, a question about keeping BT + WI-FI

### Describe alternatives you have considered.

running the .cmd to restore them, but in my case the BT one does not work.

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Additional context.

So I've installed AtlasOS, everything was fine but I found that the BT is disabled (and WIFI), managed to get WIFI Back up from the atlas folder, but the BT not, this is a Desktop PC I am running, not a laptop but still on the no. of laptops in the world, there should be a question in the wizard if you want to go through the headaches.
In my case, if I had the option to not remove BT and WIFI everything would have been perfect.

**Comment by JayXTQ** [comment]
Can you clarify what `BT` means?

**Comment by JayXTQ** [comment]
Also, have you tried drivers?

**Comment by rwkyyy** [comment]
> Can you clarify what `BT` means?

Bluetooth

> Also, have you tried drivers?

Yes, I have a thread on Discord: https://discord.com/channels/795710270000332800/1101055388675227648

**Comment by JayXTQ** [comment]
seems like in that thread everything is fixed?

**Comment by rwkyyy** [comment]
> seems like in that thread everything is fixed?

No, the issue still is, I gave you the link so you can read it and see the history

**Comment by gdnzz** [comment]
as we already talked, this is prob caused by you installing atlas on your current windows.

**Comment by rwkyyy** [comment]
> as we already talked, this is prob caused from you installing atlas on your current windows.
well it did not say anywhere that you can't use it on an existing install, but if there was a question in the first place this would not have been the case!

**Comment by gdnzz** [comment]
> > as we already talked, this is prob caused from you installing atlas on your current windows.
> > well it did not say anywhere that you can't use it on an existing install, but if there was a question in the first place this would not have been the case!

Well because technically you still can, but it is not recommended. That's why both the docs and video show you to install windows first.

**Comment by gdnzz** [comment]
also the way you titled and described your issue is completely unrelated to what youre having lol

**Comment by rwkyyy** [comment]
> Also, the way you titled and described your issue is completely unrelated to what you're having, lol. Your issue is bat files in atlas folder not working properly, I think. You will have a better Atlas experience when you clean install anyway, so it is worth the wait.

Might be so, but you can't deny that if there was an option in the setup to not remove the BT+WIFI, this would have not have happen.

I just posted a suggestion, not an obligation, it's indeed tailored to my experience and some of the unrelated stuff was not mentioned because I considered, at that point, unrelated.

**Comment by JayXTQ** [comment]
@Xyueta maybe something to peak into

**Comment by Xyueta** [comment]
It is not removing either Bluetooth or Wi-Fi connectivity, where is that coming from?

Bluetooth is disabled on default, but can be enabled in the Atlas folder on Desktop.
Wi-Fi is always enabled on default.

**Comment by Xyueta** [comment]
Also the clean install is always recommended.

Read the documentation: https://docs.atlasos.net

**Comment by JayXTQ** [comment]
Bro, they fucking toggled the wifi/bt on in the files

**Comment by Xyueta** [comment]
He only noted the Bluetooth one that is already fixed in the latest commit.

**Comment by gdnzz** [comment]
wifi already is enabled by default which is like %90 of users use, and bluetooth is optional after install anyway. His problem was deeper than wifi/bt enabling prompt, and it is fixed now.

**Comment by gopzhe** [comment]
finially how to fix this issue, reinstall windows?
