### ISSUE TITLE
[BUG REPORT] - Random shut down

### ISSUE THREAD

**Issue by MisutaHiro** [Atlas-OS/Atlas#850]
### Description

When Im playing games my laptop randomly shuts down, when I turn it on it says no battery and 255% of batter is available + any usb ports don’t work, everything backs to normal after I restart laptop. Also I notice that my laptop is very hot when it’s happening. 

### Steps to reproduce (add screenshots if applicable)

I cannot ss this bug

### Expected behavior

Normal playing

### Actual behavior (add screenshots if applicable)

Random shuts down

### Atlas Version

Atlas 10 22H2

### Desktop information

I5-2450
8gb
225 ssd
GeForce 630M with newest game ready drivers 

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

EDIT: I REPAIRED IT, JUST NEEDED TO INSTALL DROVERS BY PROGRAM THAT DEVELOPERS OF ATLAS OS RECOMMENDED

**Comment by GreatestMuslim** [comment]
This could be a hardware issue. You can try installing stock Windows 10 or Windows 11 and try playing on there. If the issue persists, It is most likely a hardware issue.

**Comment by notdido** [comment]
Your Laptop is most likely overheating.

**Comment by MisutaHiro** [comment]
> Your Laptop is most likely overheating. The battery probably shuts down after the high temparature is achieved and wont work until the temperature is lowered

I repaired it, I had to install drivers using program that atlas is recommended.

**Comment by JayXTQ** [comment]
Seems like this is fixed, if not please comment otherwise and I will reopen

**Comment by gigachdd** [comment]
Please help. I'm having the same problem. I already posted it here on github.

**Comment by TheFalseInformation** [comment]
This error still exists. I have the same problem. 
Dual Boot: Windows 10 and MacOS Monterey.
MacOS runs pretty well and doesn't crash.
Windows crashes when playing games.
I played Warzone and after about 20-40 Mins the PC crashes and immediately turns on again.

**Comment by GaucovyAero** [comment]
> This error still exists. I have the same problem. Dual Boot: Windows 10 and MacOS Monterey. MacOS runs pretty well and doesn't crash. Windows crashes when playing games. I played Warzone and after about 20-40 Mins the PC crashes and immediately turns on again.

your pc is most probably overheating, or maybe your power supply cant keep up, try searching on the internet for more info on how to diagnose it

**Comment by TheFalseInformation** [comment]
> > This error still exists. I have the same problem. Dual Boot: Windows 10 and MacOS Monterey. MacOS runs pretty well and doesn't crash. Windows crashes when playing games. I played Warzone and after about 20-40 Mins the PC crashes and immediately turns on again.
> 
> your pc is most probably overheating, or maybe your power supply cant keep up, try searching on the internet for more info on how to diagnose it

I searched in the internet. Most people say, its an OS Issue. The PSU is a piece of crap, but it can keep up. The PC crashes and instantly Restarts. No component overheats. In MacOS nothing happens. What files of Windows get edited by AstraOS?

**Comment by GaucovyAero** [comment]
> > > This error still exists. I have the same problem. Dual Boot: Windows 10 and MacOS Monterey. MacOS runs pretty well and doesn't crash. Windows crashes when playing games. I played Warzone and after about 20-40 Mins the PC crashes and immediately turns on again.
> > 
> > 
> > your pc is most probably overheating, or maybe your power supply cant keep up, try searching on the internet for more info on how to diagnose it
> 
> I searched in the internet. Most people say, its an OS Issue. The PSU is a piece of crap, but it can keep up. The PC crashes and instantly Restarts. No component overheats. In MacOS nothing happens. What files of Windows get edited by AstraOS?

well, list your system specs then

**Comment by TheFalseInformation** [comment]
CPU: i5-3470S
GPU: RX-570 8GB
RAM: 8GB Micron
PSU: Codegen 400w ATX
SSD: SanDIsk Ultra 128GB SSD, Toshiba 128GB SSD (MACOS)

**Comment by GaucovyAero** [comment]
> CPU: i5-3470S GPU: RX-570 8GB RAM: 8GB Micron PSU: Codegen 400w ATX SSD: SanDIsk Ultra 128GB SSD, Toshiba 128GB SSD (MACOS)

![130612a](https://github.com/Atlas-OS/Atlas/assets/85581164/5bdac846-8867-45bc-9cef-c8e85cf93b36)

i assume you have the PSU on the picture right here, so
the 12V rail is responsible for powering your CPU, GPU and other essential components. 12V × 12A = 144W, so this is basically just a 144W scam power supply. FYI, the 5V rail is responsible for powering the USBs and other non-vital stuff.

![image](https://github.com/Atlas-OS/Atlas/assets/85581164/62877d52-334d-4a65-81f0-648cab9143ac)

in comparison to your power supply, here is an EVGA 400W power supply, 12V × 30A = 360W, which is more than double compared to what your scam power supply can deliver

heres a good educational video showcasing this issue:

https://www.youtube.com/watch?v=SX0LjqdGvxs

**Comment by TheFalseInformation** [comment]
> > CPU: i5-3470S GPU: RX-570 8GB RAM: 8GB Micron PSU: Codegen 400w ATX SSD: SanDIsk Ultra 128GB SSD, Toshiba 128GB SSD (MACOS)
> 
> ![130612a](https://private-user-images.githubusercontent.com/85581164/292918782-5bdac846-8867-45bc-9cef-c8e85cf93b36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MjUzNTMsIm5iZiI6MTcwMzYyNTA1MywicGF0aCI6Ii84NTU4MTE2NC8yOTI5MTg3ODItNWJkYWM4NDYtODg2Ny00NWJjLTljZWYtYzhlODVjZjkzYjM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDIxMTA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzNWJlNmI2ZTJhMGY3MjE5Yjg2NzU2OWJiMmUxYTgyOGM5ODgxNjZiMmIxNGQ2MzQyNDdhYjU1NmZjZWExOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fblf1THQh4o_3hKlAqZEacPjTeo-MkO2AH3YNoDHtTI)
> 
> i assume you have the PSU on the picture right here, so the 12V rail is responsible for powering your CPU, GPU and other essential components. 12V × 12A = 144W, so this is basically just a 144W scam power supply. FYI, the 5V rail is responsible for powering the USBs and other non-vital stuff.
> 
> ![image](https://private-user-images.githubusercontent.com/85581164/292919078-62877d52-334d-4a65-81f0-648cab9143ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MjUzNTMsIm5iZiI6MTcwMzYyNTA1MywicGF0aCI6Ii84NTU4MTE2NC8yOTI5MTkwNzgtNjI4NzdkNTItMzM0ZC00YTY1LTgxZjAtNjQ4Y2FiOTE0M2FjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDIxMTA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0ZGZhZWU2NjA4Zjg4ZTk2NDlkMWE0NTFhYzQ3Y2UxNWZmZTgzMjUwNWU0ZTk2MzhmMmY1ZGNlN2VjOGFlYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ez2opQIQOavD_jjIqMF7xwxLf6JdXj_f7TwfYmX0ky4)
> 
> in comparison to your power supply, here is an EVGA 400W power supply, 12V × 30A = 360W, which is more than double compared to what your scam power supply can deliver
> 
> heres a good educational video showcasing this issue:
> 
> https://www.youtube.com/watch?v=SX0LjqdGvxs
> 
> **recommended power supply wattage for the RX 570 8GB is a 500W one, something that actually has 400W+ on the 12V rail**

Thank you. The video is recommended to watch. Now I know what's wrong with this Chinese firecracker.
